apiversion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecom-app
data:
  APP_ENV: "devolopment"
  PORT: "5000"
  LOG_LEVEL: "debug"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ecom_db"