apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-db.yaml
  - deployment.yaml
  - service.yaml
  - ../ingress/ingress.yaml